language: python
python:
    - "2.7"
services: mongodb
env:
    global:
      - PYTHONENV=/home/travis/virtualenv/python2.7.9
      - BUILD_DIR=${TRAVIS_BUILD_DIR}
    matrix:
      - TRAVIS_MODE=1
addons:
  apt:
    packages:
      - swig
      - libxml2-dev
      - libxslt1-dev
      - libxmlsec1-dev
      - libfreetype6-dev
      - python-pip
      - python-apt
      - python-dev
      - gfortran
      - libopenblas-dev
      - liblapack-dev

before_install:
    - export DJANGO_SETTINGS_MODULE=test-settings

cache:
  directories:
    - $PYTHONENV

# command to install dependencies
install:
    - ./pip_install_local.sh

# command to run tests and quality checks
script:
    - ./copy_edx_dependencies.sh
    - ./run_tests.sh

branches:
    only:
        - master
        - xapi
        - travis

after_success: coveralls
