language: python

python:
    - "2.7"

env:
    - TRAVIS_MODE=1

before_install:
    - export DJANGO_SETTINGS_MODULE=settings

# command to install dependencies
install:
    - "pip install coveralls"
    - "pip install pep8"
    - "pip install pylint"
    - "pip install -r requirements.txt"

# command to run tests and quality checks
script:
    - coverage run --source=oai ./manage.py test
    - coverage report -m
    - pep8 --config=.pep8 oai
    - pylint --rcfile=.pylintrc oai --report=no
    - pep8 --config=.pep8 ecoapi
    - pylint --rcfile=.pylintrc ecoapi --report=no

branches:
    only:
        - master
        - travis

after_success: coveralls
